version: '3'

services:
  data-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=data_user
      - POSTGRES_PASSWORD=data_password
    volumes:
      - ./data-db:/var/lib/postgresql/data

  metabase-app-db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase_user
      - POSTGRES_PASSWORD=metabase_password
    volumes:
      - ./metabase-app-db:/var/lib/postgresql/data

  metabase-app:
    image: metabase-arm:latest
    restart: always
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase_user
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=metabase-app-db
    depends_on:
      - metabase-app-db
    links:
      - metabase-app-db
    ports:
      - "3000:3000"

  pgadmin-app:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@metabase.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"